// vue/src/views/About.vue
<template>
  <div>
    <h2>About</h2>

    <p class="mb-1em">
      This is a simple project created to compare different frontend frameworks.
    </p>

    <p class="mb-2em">
      It have been developed as part of the Epic Friday initiative. Wanna know
      more? Visit
      <a href="https://www.epiclabs.io/" target="_blank">EpicLabs</a> now!
    </p>

    <p>-- Adrian Caballero (2020)</p>
  </div>
</template>

// gatsby/src/pages/about.tsx
import React from 'react';
import Layout from '../components/layout';

export default () => (
  <Layout>
    <h2>About</h2>

    <p className="mb-1em">This is a simple project created to compare different frontend frameworks.</p>

    <p className="mb-2em">It have been developed as part of the Epic Friday initiative. Wanna know more? Visit <a href="https://www.epiclabs.io/" target="_blank">EpicLabs</a> now!</p>

    <p>-- Adrian Caballero (2019)</p>
  </Layout>
)
