// vue/src/views/About.vue
<template>
  <div>
    <h2>About</h2>

    <p class="mb-1em">
      This is a simple project created to compare different frontend frameworks.
    </p>

    <p class="mb-2em">
      It have been developed as part of the Epic Friday initiative. Wanna know
      more? Visit
      <a href="https://www.epiclabs.io/" target="_blank">EpicLabs</a> now!
    </p>

    <p>-- Adrian Caballero (2020)</p>
  </div>
</template>

// angular/src/app/pages/about/about.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-about',
  templateUrl: 'about.component.html',
  styles: [],
})
export class AboutComponent { }

<h2>About</h2>

<p class="mb-1em">This is a simple project created to compare different frontend frameworks.</p>

<p class="mb-2em">It have been developed as part of the Epic Friday initiative. Wanna know more? Visit <a href="https://www.epiclabs.io/" target="_blank">EpicLabs</a> now!</p>

<p>-- Adrian Caballero (2019)</p>
