// angular/src/app/pages/home/home.component.ts
import { Component, OnInit } from '@angular/core';
import { RickAndMortyService, IRamCharacter, IRamPaginatedCharacters } from 'src/app/services/rick-and-morty.service';

@Component({
  selector: 'app-home',
  templateUrl: 'home.component.html',
  styles: [],
})
export class HomeComponent implements OnInit {

  characters: IRamCharacter[] = [];

  constructor(private ramService: RickAndMortyService) {
    // nothing to see here
  }

  ngOnInit() {
    this.ramService.getCharacters().subscribe((page: IRamPaginatedCharacters) => {
      this.characters = page.results;
    });
  }

}

<h2>Rick and Morty characters</h2>

<div class="card-container">
  <div class="card" *ngFor="let character of characters">
    <div class="card-content">
      <img [src]="character.image">
      <div class="card-info">
        <p class="text-center bold">{{character.name}}</p>
        <p class="text-center">{{character.gender}} {{character.species}}</p>
        <ul>
          <li>Origin: {{character.origin.name}}</li>
          <li>Location: {{character.location.name}}</li>
          <li>Episodes: {{character.episode.length}}</li>
        </ul>
      </div>
    </div>
  </div>
</div>

// vue/src/views/Home.vue
<template>
  <div>
    <h2>Rick and Morty characters</h2>

    <div class="card-container">
      <div
        class="card"
        v-for="character in characters"
        v-bind:key="character.name"
      >
        <div class="card-content">
          <img v-bind:src="character.image" />
          <div class="card-info">
            <p class="text-center bold">{{ character.name }}</p>
            <p class="text-center">
              {{ character.gender }} {{ character.species }}
            </p>
            <ul>
              <li>Origin: {{ character.origin.name }}</li>
              <li>Location: {{ character.location.name }}</li>
              <li>Episodes: {{ character.episode.length }}</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import axios from "axios";

export default {
  data() {
    return {
      characters: null
    };
  },
  mounted() {
    axios.get("https://rickandmortyapi.com/api/character/").then(response => {
      this.characters = response.data.results;
    });
  }
};
</script>
